### PR TITLE
Enhance add conference field

### PR DESCRIPTION
**Pull request by StewPoll**
This PR's main contribution is to add in support for the `CONFERENCE` property that was added in RFC 7986. [Source](https://tools.ietf.org/html/rfc7986#section-5.11).

This PR also does the follow as minor contributions:

- Updates Copyright year in the readme
- Updates `setImage` so that it can be used in a chain like manner, like other `set` functions on the `CalendarEvent` class.

### CODE REVIEW

**Comment by StewPoll** [comment]
No Travis running on this repo?

**Comment by jasvrcek** [comment]
@StewPoll thank you for work! I have just one nitpick change I would like you to make before merging - can you change the CalendarEvent $conference property to "$conferences", and also change the getter and setter to getConferences and setConferences?

I saw your comment about the STATUS validation issue, it would be great if you could also go ahead and make your suggested update for that.

(Fyi Travis is running, check the build badge on the code homepage readme. Here's the Travis link: https://travis-ci.org/github/jasvrcek/ICS)

**Comment by StewPoll** [comment]
No worries @jasvrcek about `conferences` - All done.

I'll look into the Status stuff when I get a chance. I'll leave my thoughts on that issue though.

**Comment by jasvrcek** [comment]
@StewPoll great, thanks!

**Pull request merged**
