### PR TITLE
Add the ReturnTypeWillChange attribute on the iterator

### PR DESCRIPTION
**Pull request by stof**
This avoids getting a deprecation warning on PHP 8.1

### CODE REVIEW

**Comment by stof** [comment]
a semver-major version will be needed at some point to add actual return types on those methods (which will require bumping the min PHP requirement to at least 7.2 to have support for variance rules). The release date of PHP 9.0 is not known yet but it will require the return types.

**Comment by stof** [comment]
And it is a semver-major (so 0.9.0 or 1.0 currently) because this class is neither internal nor final, so adding return types is a BC break for classes that might extend it.

**Comment by jasvrcek** [comment]
@stof yes - done!

**Comment by stof** [comment]
thanks

**Pull request merged**
