### PR TITLE
bymonth-bymonthday

### PR DESCRIPTION
**Pull request by AgamlaRage**
Here is the pull-request related to this issue https://github.com/jasvrcek/ICS/issues/23

Thx

### CODE REVIEW

**Comment by jasvrcek** [comment]
@AgamlaRage looks good, but could you do two more things?

1. Delete the @todo on line 94.
2. Add a new assertion that tests the new bymonth feature to the testParse method in https://github.com/jasvrcek/ICS/blob/master/tests/Model/Recurrence/RecurrenceRuleTest.php.

I really appreciate your help!

**Comment by jasvrcek** [comment]
@AgamlaRage Oops, for #2 I meant to say add a new assertion to testToString in RecurrenceRuleTest, not testParse - sorry about that. If you want to add the parsing functionality that's cool, but not necessary - I would think of that as a separate issue.

**Comment by AgamlaRage** [comment]
Humm, I prefere that you do it because I think I didn't understand the tests part yet, I'm not really accustomed with tests.
I will follow the commit so I can see what you mean, and what the tests need !

**Comment by jasvrcek** [comment]
@AgamlaRage all set - thanks again!

**Comment by AgamlaRage** [comment]
Same for me, thx for the reactivity ! :)

**Pull request merged**
