### PR TITLE
passed through PHP Coding Standards Fixer

### PR DESCRIPTION
**Pull request by gam6itko**
Compatible with PSR-2 
tool page http://cs.sensiolabs.org/

### CODE REVIEW

**Comment by jasvrcek** [comment]
Hi @gam6itko, thanks for doing this coding standards update. Would you also be willing to update the composer.json and travis.yml to drop php 5.3 support, since travis no longer supports php 5.3 by default? (That's why the check is failing)

**Comment by gam6itko** [comment]
@jasvrcek I can try

**Comment by gam6itko** [comment]
@jasvrcek I've done

**Comment by jasvrcek** [comment]
Thanks @gam6itko!

**Pull request merged**
