### PR TITLE
Revert "Fix VTIMEZONE to work in Outlook when using CalendarExport::setDateTimeFormat"

### PR DESCRIPTION
**Pull request by jasvrcek**
Reverts jasvrcek/ICS#47

### CODE REVIEW

**Comment by adamroyle** [comment]
Can this issue be re-opened? I am having similar issues with Outlook and Apple Calendar and currently am using a hack to get around this timezone weirdness.

**Comment by jasvrcek** [comment]
@adamroyle sure, could you explain the hack you are having to use?

**Comment by adamroyle** [comment]
Forgive my naivety since timezones (and time in general) are not my specialty!

When creating an ics file and adding it to Apple Calendar or Outlook, the VTIMEZONE seems to be ignored so the events are created in the current users timezone, rather than the ics timezone.

eg. Here is what is generated by default. When adding this to my calendar, it appears as 9:30am Brisbane time (+1000), although it should be 8:30am since Sydney is currently +1100 (due to DST).
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//AcmeGroup//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:Australia/Sydney
BEGIN:STANDARD
DTSTART:19691231T140000
TZOFFSETTO:+1000
TZOFFSETFROM:+1000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
UID:AcmeGroup265
DTSTART:20200211T093000
DTEND:20200211T100000
STATUS:
SUMMARY:Half year results to 31 December 2019
DESCRIPTION:
DTSTAMP:20200212T034328Z
CREATED:20200102T025821Z
LAST-MODIFIED:20200211T071432Z
END:VEVENT
END:VCALENDAR
```

If I explicitly set a timezone inside the BEGIN:VEVENT block, it works as expected. eg.

```
DTSTART;TZID="Australia/Sydney":20200211T093000
DTEND;TZID="Australia/Sydney":20200211T100000
```

Now, in trying to explain this, I have realised that the timezone offset above indicates +1000 with no mention of when DST should take effect. 

Looking at the source code that generates the DST changes, I found this code that has 1970 hardcoded. 

```php
$tz->getTransitions(strtotime('1970-01-01'), strtotime('1970-12-31'));
```

Changing the end date to `2018-12-31` adds a DST change for Sydney. eg.

```
BEGIN:VTIMEZONE
TZID:Australia/Sydney
BEGIN:STANDARD
DTSTART:20180331T160000
TZOFFSETTO:+1000
TZOFFSETFROM:+1000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20181006T160000
TZOFFSETTO:+1100
TZOFFSETFROM:+1000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
END:VTIMEZONE
```

However this still didn't add the event at the right time when adding to Apple Calendar. At this stage, the only way I have found to get the right time, is to add the TZID to each event. In my code, I am just modifying the ics string with a regex before outputting to the client.

Hope this helps!

**Comment by jasvrcek** [comment]
@adamroyle would you have time to work on this? If you can create a pull request I will merge it in. I'm going on vacation next week and won't have much time to work on this issue myself when I get back.

**Comment by adamroyle** [comment]
@jasvrcek after checking out the repo and running the tests, I realised that the version I was testing with (0.6 from packagist) did not contain the latest code changes in github. The tests were failing due to the current year being 2020 rather than 2019 when the tests were run in Travis.

I have opened a pull request to fix the tests, however haven't changed any functionality in the calendar export itself. 

Looking at the code, I believe the current unreleased changes would be enough to fix my issue, so are you able to cut a new release?

**Comment by jasvrcek** [comment]
@adamroyle sorry for the delay! Thanks for your work, I've merged and tagged a new release.

**Pull request merged**
